class Image

	@image

	def initialize(width = 400, height = 400)
		@image = Array.new(width) do |i|
			i = Array.new(height) do |j|
				j = Pixel.new
			end
		end
		puts "#{@image[0].size}x#{@image.size}"
	end

	def apply(p, brush)
		# !! Effets de bord
		# for i in ([p.y - (brush.size - brush.anchor.y),0].max, [p.y + (brush.size - brush.anchor.y), @image.size].max)
		# @image[p.x][p.y] = Pixel.new(brush.color)
		@image[p.x][p.y] = Pixel.new(Color.new(0,255,0))
			
		# end

	end

	def save(fn)
		ext = fn.split('.')[-1]
		if ext == "ppm"
			File.open(fn, 'w') do |f|

				f << "P3\n"
				f << "# This image was generated by Kandinsky\n"
				f << "#{@image[0].size} #{@image.size}\n"
				f << "255\n"

				@image.each do |line|
					line.each do |p|
						c = p.color
						f << "#{c.r} #{c.g} #{c.b} "
					end
					f << "\n"
				end
			end
		end
	end

	def to_s
		"#{@image}"
	end

end